### PR TITLE
Feature/rabbitmq docker update

### PR DESCRIPTION
**Pull request by Thomas-Mildner**
- Updated Dockerfile:
 --> Use base Rabbitmq Image 3.8.3

- Updated to new rabbitmq.conf file format

### CODE REVIEW

**Review by jonathandandries — CHANGES_REQUESTED** [review]
Hello Tomas,

Thanks for this pull request. You are on the right track with changes, but I've noticed the following items:
1. The logins don't work. My recommendation would be to remove custom_definitions locally, rebuild and re-run the image, and then export a new version of custom_definitions.json to use in the image. Here is why:
    1-1. You have added a guest|guest user in rabbitmq.conf, but that user has not been added to custom_definitions.json, so it is not allowed to log in. You can make it work by removing customer_definitions.json and rebuilding the image, but a better approach would be to add the credentials to custom_defintions.json because,
    1-2. The admin|nimda login doesn't work either because the password hashing algorithm has changed in the new version of RabbitMQ. This needs to be updated in custom_definitions along with a number of other settings.

The point of this example code is to show how you can use custom_definitions.json to deploy a pre-conigured version of RabbitMQ. If you can updated custom_definitions.json to the correct values for the new version of RabbitMQ, this would be a much stronger pull request.

2. The rabbit MQ client image has not been upgraded. Can you update it to the latest version so that the example shows how you can connect from another image?

Cheers,

Jonathan

**Comment by Thomas-Mildner** [comment]
Thanks for your Review. I will do the suggested changes :)

**Comment by Thomas-Mildner** [comment]
Hello Jonathan,

i`ve updated my pull request:

My Changes are:
1) Server
- Username was changed to admin and password is nimda
- i`ve created the default vhost, exchange and queue as originally designed in your repo
2) Client
- Updated Client Dockerfile to version 3.8.3
- Regenerated rabbitmq admin file from Rabbitmq.3.8.3-management instance

Can you please review my changes and give me some feedback?

Thanks, have a great day!

**Comment by jonathandandries** [comment]
Thanks Tomas,

This is good. I'll merge this in, and then I'm going to fix bash-completion in the client, correct the example exchange (put it in the example-vhost) and add binding from example-exchange to example-queue, and update README for new stuff. You can re-pull from me if you want these updates.

**Pull request merged**
